---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: "Test: packages ansible-lint"
      block:
        - name: "Get pipx installed  packages"
          ansible.builtin.command: "pipx list --json"
          environment:
            PIPX_HOME: "/opt/pipx"
          changed_when: false
          register: pipx_installed_packages

        - name: "Set fact"
          ansible.builtin.set_fact:
            pipx_simple_list: "{{ pipx_simple_list | default({}) | combine({item.key: item.value.metadata.main_package.package_version}) }}"
          loop: "{{ pipx_installed_packages.stdout | from_json | json_query('venvs') | dict2items }}"

        - name: "Verify packages ansible-lint"
          ansible.builtin.assert:
            that:
              - pipx_simple_list['ansible-lint'] is defined

        - name: "Print installed packages"
          ansible.builtin.debug:
            msg: "{{ pipx_simple_list }}"
